version: "3"
services:
  mysql_udf:
    build: .
    container_name: mysql_udf
    ports:
      - "26425:3306"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    volumes:
      - ./db/data/:/var/lib/mysql
      - ./src/:/mysqludf
      - ./db/cache:/mysqludf/cache

  adminer:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql_udf
      - PMA_PORT=3306
    ports:
      - 26426:80

  workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    restart: always
    environment:
      PGID: 1000
      PUID: 1000
    ports:
      - 3001:3001
      - 3000:3000